/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArmaTuTalunaRouteImport } from './routes/arma-tu-taluna'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArmaTuTalunaRoute = ArmaTuTalunaRouteImport.update({
  id: '/arma-tu-taluna',
  path: '/arma-tu-taluna',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arma-tu-taluna': typeof ArmaTuTalunaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arma-tu-taluna': typeof ArmaTuTalunaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arma-tu-taluna': typeof ArmaTuTalunaRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/producto/$slug': typeof ProductoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arma-tu-taluna' | '/categoria/$slug' | '/producto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arma-tu-taluna' | '/categoria/$slug' | '/producto/$slug'
  id:
    | '__root__'
    | '/'
    | '/arma-tu-taluna'
    | '/categoria/$slug'
    | '/producto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArmaTuTalunaRoute: typeof ArmaTuTalunaRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arma-tu-taluna': {
      id: '/arma-tu-taluna'
      path: '/arma-tu-taluna'
      fullPath: '/arma-tu-taluna'
      preLoaderRoute: typeof ArmaTuTalunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArmaTuTalunaRoute: ArmaTuTalunaRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ProductoSlugRoute: ProductoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
